In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier 
from sklearn import preprocessing


In [2]:
df = pd.read_csv("E:/games/IISc-May-2019/HAPT Data Set/FeatureSet/200feature_Dataset.csv",header=None)
y = df.loc[:,200]
X = df.loc[:,0:199]
# y = df.loc[:,100]
# X = df.loc[:,0:99]
# X.loc[:,:49] = X.loc[:,:49]*1e5        #Scaling 
# X.loc[:,100:149] = X.loc[:,100:149]*1e5    #Scaling
min_max_scaler = preprocessing.MinMaxScaler()
standard_scaler = preprocessing.StandardScaler()
X = standard_scaler.fit_transform(X)





uci_X = pd.read_csv("E:/games/IISc-May-2019/HAPT Data Set/Train/X_train.csv")
uci_y = pd.read_csv("E:/games/IISc-May-2019/HAPT Data Set/Train/y_train.csv")
# uci_X = uci_X.sample(frac=1).reset_index(drop=True)
# uci_y = uci_y.sample(frac=1).reset_index(drop=True)
uci_X = uci_X.loc[0:5000,:]
uci_y = uci_y.loc[0:5000,:]


# wong = pd.read_csv("E:/games/IISc-May-2019/wong/FeatureSet/Dataset.csv",header=None) # Wong is useless
# wong_X = wong.loc[:,0:99]
# wong_y = wong.loc[:,100] 




print(X.shape)
# print(X.head(10))

(6068, 200)


In [58]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.96, shuffle=True) 
print(y_test.shape,y_train.shape)

(243,) (5825,)


C:\Users\HP\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [14]:
dtree_model = DecisionTreeClassifier(max_depth = 2).fit(X_train, y_train) 
dtree_predictions = dtree_model.predict(X_test) 
accuracy = dtree_model.score(X_test, y_test) 

# creating a confusion matrix 
cm = confusion_matrix(y_test, dtree_predictions)

print(accuracy)
cm

0.3950617283950617


array([[29,  0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [11,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 5,  0, 17,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 41,  4,  0,  0,  0,  0,  0,  0],
       [ 1,  0,  0,  0, 36,  1,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  1,  0, 32, 14,  0,  0,  0,  0,  0,  0],
       [ 1,  0, 10,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 2,  0,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  6,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  8,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  6,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0]], dtype=int64)

In [59]:
from sklearn.svm import SVC 
# svm_model_linear = SVC(kernel = 'linear', C = 10).fit(X_train, y_train)  #lesser the c hyperparameter , softer the margin
                                                                            #higher c means hard margin

    
# (0.008,10) < (0.008,100)(79,74) < (0.01,10)(76,74)
svm_model_linear = SVC(kernel = 'rbf', gamma=.014, C = 100).fit(X_train, y_train)#gamma makes bell shaped curve narrower and as 
# a result influence of each term becomes smaller. Increasin gamma may lead to overfitting

#The RBF kernel SVM decision region is actually also a linear decision region. What RBF kernel SVM actually does is to create 
# non-linear combinations of your features to uplift your samples onto a higher-dimensional feature space where you can use a 
# linear decision boundary to separate your classes




# svm_model_linear = SVC(kernel = 'poly', degree=3, coef0=100, C = 5).fit(X_train, y_train)#coef0 controls how much our model is 
                                                                            #influenced by high degree poly vs low degree poly
svm_predictions = svm_model_linear.predict(X_test) 
  
# model accuracy for X_test   
accuracy = svm_model_linear.score(X_test, y_test) 
  
# training accuracy
taccu = svm_model_linear.score(X_train, y_train)

# creating a confusion matrix 
cm = confusion_matrix(y_test, svm_predictions)

print(taccu)
print(accuracy)

cm

0.7998283261802576
0.7654320987654321


array([[34,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1, 20,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 21,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 19, 26,  5,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1, 35,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  7, 13, 15,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  1,  0,  0,  0,  7,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  7,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  5,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  6,  0,  0],
       [ 0,  0,  1,  0,  0,  0,  0,  0,  1,  0,  8,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  9]], dtype=int64)

In [17]:
# training a KNN classifier 
from sklearn.neighbors import KNeighborsClassifier 
knn = KNeighborsClassifier(n_neighbors = 7).fit(X_train, y_train) 

cm = confusion_matrix(y_test, knn.predict(X_test))

# training accuracy
taccu = knn.score(X_train, y_train)

# accuracy on X_test
accuracy = knn.score(X_test, y_test)

print(taccu)
print(accuracy)
cm

0.8401716738197424
0.7901234567901234


array([[29,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  9,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  3, 18,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 31,  7,  7,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  4, 32,  2,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  6,  6, 35,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 10,  1,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0,  0,  0,  4,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  4,  1,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  1,  6,  0,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  6,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  8]], dtype=int64)

In [ ]:
# training a Naive Bayes classifier 
from sklearn.naive_bayes import GaussianNB 
gnb = GaussianNB().fit(X_train, y_train) 
gnb_predictions = gnb.predict(X_test) 

# training accuracy
taccu = gnb.score(X_train, y_train)

# accuracy on X_test 
accuracy = gnb.score(X_test, y_test) 

print(taccu)
print(accuracy) 

In [ ]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import LinearSVC
clf = OneVsRestClassifier(LinearSVC(random_state=0)).fit(X_train, y_train)
clf_predictions = clf.predict(X_test)

# training accuracy
taccu = clf.score(X_train, y_train)


# accuracy on X_test 
cm = confusion_matrix(y_test, clf_predictions)
accu = clf.score( X_test, y_test )


print(taccu)
print(accu)
cm

In [ ]:
from sklearn import linear_model
clf = linear_model.SGDClassifier(max_iter=4000, tol=1e-3)
clf.fit( X_train, y_train )

# training accuracy
taccu = clf.score(X_train, y_train)


# accuracy on X_test 
cm = confusion_matrix(y_test, clf_predictions)
accu = clf.score( X_test, y_test )


print(taccu)
print(accu)
cm

In [ ]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn import linear_model
clf = OneVsRestClassifier(linear_model.SGDClassifier(max_iter=4000, tol=1e-3))
clf.fit( X_train, y_train )

# training accuracy
taccu = clf.score(X_train, y_train)


# accuracy on X_test 
cm = confusion_matrix(y_test, clf_predictions)
accu = clf.score( X_test, y_test )


print(taccu)
print(accu)
cm