In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier 
from sklearn import preprocessing
from sklearn.model_selection import cross_val_score
from window_slider import Slider
from scipy import signal


In [2]:
df = pd.read_csv("E:/games/IISc-May-2019/HAPT Data Set/FeatureSet/HypIMU_time_0overlap_feature_Dataset.csv",header=None)
df = df.sample(frac=1)



# y = df.loc[:,108]    #for 30 features
# X = df.loc[:,0:107]

# y = df.loc[:,200]    #for 200 features
# X = df.loc[:,0:199]  


y = df.loc[:,30]    #for 30 features
X = df.loc[:,0:29]

# y = df.loc[:,100]    #for 100 features
# X = df.loc[:,0:99]


# y = df.loc[:,60]      #for 60 or 60-0 features
# X = df.loc[:,0:59]

# y = df.loc[:, 36]        #for 36-0 features
# X = df.loc[:, 0:35]

# y = df.loc[:,120]      #for 60-60 features
# X = df.loc[:,0:119]


# min_max_scaler = preprocessing.MinMaxScaler()
standard_scaler = preprocessing.StandardScaler()
X = standard_scaler.fit_transform(X)





uci_X = pd.read_csv("E:/games/IISc-May-2019/HAPT Data Set/Train/X_train.csv")
uci_y = pd.read_csv("E:/games/IISc-May-2019/HAPT Data Set/Train/y_train.csv")

# uci_X = uci_X.sample(frac=1).reset_index(drop=True)
# uci_y = uci_y.sample(frac=1).reset_index(drop=True)
uci_X = uci_X.loc[0:5000,:]
uci_y = uci_y.loc[0:5000,:]


print(X.shape)
print(y.head)
# y

(437, 30)
<bound method NDFrame.head of 54     1
376    5
229    2
2      1
91     1
216    2
113    1
315    3
239    2
70     1
6      1
281    3
23     1
0      1
346    4
224    2
114    1
61     1
291    3
172    1
37     1
194    2
108    1
184    2
282    3
187    2
236    2
271    3
136    1
250    2
      ..
203    2
400    5
305    3
377    5
225    2
103    1
45     1
251    2
133    1
317    3
209    2
235    2
352    4
182    2
348    4
47     1
333    4
160    1
62     1
214    2
193    2
207    2
205    2
270    3
433    5
177    1
332    4
30     1
179    1
367    5
Name: 30, Length: 437, dtype: int64>


In [11]:
from sklearn.svm import SVC

# clf = SVC(kernel='linear', C=100 )
clf = SVC( kernel = 'rbf', gamma=.01, C = 10, decision_function_shape = 'ovr' )

scores = cross_val_score(clf, X, y, cv=5)
print(scores.mean())
scores


0.9337147415997382


array([0.91111111, 0.95505618, 0.93181818, 0.90588235, 0.96470588])

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.9, shuffle=True) 
print(y_test.shape,y_train.shape)

(44,) (393,)


C:\Users\HP\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [77]:
dtree_model = DecisionTreeClassifier(max_depth = 2).fit(X_train, y_train) 
dtree_predictions = dtree_model.predict(X_test) 
accuracy = dtree_model.score(X_test, y_test) 

# creating a confusion matrix 
cm = confusion_matrix(y_test, dtree_predictions)

print(accuracy)
cm

0.5128617363344051


array([[ 81,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ 67,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ 51,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  3,   0,   0,   0,  81,   0,   0,   0,   0,   0,   0,   0],
       [  1,   0,   0,   0, 132,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0, 105,   0,   0,   0,   0,   0,   0],
       [ 12,   0,   0,   0,   1,   0,   0,   0,   0,   0,   0,   0],
       [ 11,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ 19,   0,   0,   0,   1,   2,   0,   0,   0,   0,   0,   0],
       [ 14,   0,   0,   0,   2,   0,   0,   0,   0,   0,   0,   0],
       [ 26,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,   0],
       [ 12,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]],
      dtype=int64)

In [7]:
from sklearn.svm import SVC 
svm_model_linear = SVC(kernel = 'linear', C = 100 ).fit(X_train, y_train)  #lesser the c hyperparameter , softer the margin
                                                                            #higher c means hard margin


svm_model_rbf = SVC(kernel = 'rbf', gamma=.01, C = 10, decision_function_shape = 'ovr').fit(X_train, y_train)#gamma makes bell shaped curve narrower and as 
# a result influence of each term becomes smaller. Increasin gamma may lead to overfitting

#The RBF kernel SVM decision region is actually also a linear decision region. What RBF kernel SVM actually does is to create 
# non-linear combinations of your features to uplift your samples onto a higher-dimensional feature space where you can use a 
# linear decision boundary to separate your classes and then invert this boundary back to lower dimension.




svm_model_linear = SVC(kernel = 'poly', degree=3, coef0=100, C = 5).fit(X_train, y_train)#coef0 controls how much our model is 
                                                                            #influenced by high degree poly vs low degree poly
svm_predictions1 = svm_model_linear.predict(X_test) 
svm_predictions2 = svm_model_rbf.predict(X_test) 

# model accuracy for X_test   
accuracy1 = svm_model_linear.score(X_test, y_test) 
accuracy2 = svm_model_rbf.score(X_test, y_test) 

# training accuracy
taccu1 = svm_model_linear.score(X_train, y_train)
taccu2 = svm_model_rbf.score(X_train, y_train)

# creating a confusion matrix 
cm1 = confusion_matrix(y_test, svm_predictions1)
cm2 = confusion_matrix(y_test, svm_predictions2)

print(taccu1)
print(accuracy1)
print(cm1)

print(taccu2)
print(accuracy2)
print(cm2)

0.9949109414758269
0.9318181818181818
[[22  0  2  0  0]
 [ 0  3  1  0  0]
 [ 0  0  4  0  0]
 [ 0  0  0  5  0]
 [ 0  0  0  0  7]]
0.9720101781170484
0.9772727272727273
[[24  0  0  0  0]
 [ 0  3  1  0  0]
 [ 0  0  4  0  0]
 [ 0  0  0  5  0]
 [ 0  0  0  0  7]]


In [52]:
# training a KNN classifier 
from sklearn.neighbors import KNeighborsClassifier 
knn = KNeighborsClassifier(n_neighbors = 7).fit( X_train, y_train ) 

cm = confusion_matrix(y_test, knn.predict(X_test))

# training accuracy
taccu = knn.score(X_train, y_train)

# accuracy on X_test
accuracy = knn.score(X_test, y_test)

print(taccu)
print(accuracy)
cm

0.9646182495344506
0.9599627560521415


array([[433,   1,   6,   0,   0],
       [ 11, 175,   3,   0,   0],
       [ 19,   1, 133,   0,   2],
       [  0,   0,   0, 108,   0],
       [  0,   0,   0,   0, 182]], dtype=int64)

In [148]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=0, multi_class='ovr')
model = clf.fit(X_train, y_train)

cm = confusion_matrix(y_test, clf.predict(X_test))

# training accuracy
taccu = clf.score(X_train, y_train)

# accuracy on X_test
accuracy = clf.score(X_test, y_test)

print(taccu)
print(accuracy)
cm


C:\Users\HP\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.9723577235772358
0.9415584415584416


array([[50,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 20,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 26,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  0,  0, 43,  9,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1, 46,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 55,  0,  0,  0,  0,  0,  0],
       [ 1,  0,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  6,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 10,  0,  1,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  6,  0,  1],
       [ 0,  0,  0,  0,  0,  0,  1,  0,  0,  0, 15,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  8]], dtype=int64)

In [149]:
# training a Naive Bayes classifier 
from sklearn.naive_bayes import GaussianNB 
gnb = GaussianNB().fit(X_train, y_train) 
gnb_predictions = gnb.predict(X_test) 

# training accuracy
taccu = gnb.score(X_train, y_train)

# accuracy on X_test 
accuracy = gnb.score(X_test, y_test) 

print(taccu)
print(accuracy) 

0.9235772357723577
0.8798701298701299


In [150]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import LinearSVC
clf = OneVsRestClassifier(LinearSVC(random_state=0)).fit(X_train, y_train)
clf_predictions = clf.predict(X_test)

# training accuracy
taccu = clf.score(X_train, y_train)


# accuracy on X_test 
cm = confusion_matrix(y_test, clf_predictions)
accu = clf.score( X_test, y_test )


print(taccu)
print(accu)
cm

0.9813008130081301
0.948051948051948


C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarn

array([[51,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 20,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 26,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 45,  8,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1, 46,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 55,  0,  0,  0,  0,  0,  0],
       [ 1,  0,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  6,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 10,  0,  1,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  6,  0,  1],
       [ 0,  0,  0,  0,  0,  0,  1,  0,  0,  0, 15,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  7]], dtype=int64)

In [151]:
from sklearn import linear_model
clf = linear_model.SGDClassifier(max_iter=4000, tol=1e-3)
clf.fit( X_train, y_train )

# training accuracy
taccu = clf.score(X_train, y_train)


# accuracy on X_test 
cm = confusion_matrix(y_test, clf_predictions)
accu = clf.score( X_test, y_test )


print(taccu)
print(accu)
cm

0.9699186991869919
0.9383116883116883


array([[51,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 20,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 26,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 45,  8,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1, 46,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 55,  0,  0,  0,  0,  0,  0],
       [ 1,  0,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  6,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 10,  0,  1,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  6,  0,  1],
       [ 0,  0,  0,  0,  0,  0,  1,  0,  0,  0, 15,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  7]], dtype=int64)

In [152]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn import linear_model
clf = OneVsRestClassifier(linear_model.SGDClassifier(max_iter=4000, tol=1e-3))
clf.fit( X_train, y_train )

# training accuracy
taccu = clf.score(X_train, y_train)


# accuracy on X_test 
cm = confusion_matrix(y_test, clf_predictions)
accu = clf.score( X_test, y_test )


print(taccu)
print(accu)
cm

0.967479674796748
0.9285714285714286


array([[51,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 20,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 26,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 45,  8,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1, 46,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 55,  0,  0,  0,  0,  0,  0],
       [ 1,  0,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  6,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 10,  0,  1,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  6,  0,  1],
       [ 0,  0,  0,  0,  0,  0,  1,  0,  0,  0, 15,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  7]], dtype=int64)

In [66]:
# This is for testing on test set .


# df1
# for i in range(1,13):
# accfile = source + str(i) + acc + '.csv'
#     gyrofile = source + str(i) + gyro + '.csv'
#     df1 = pd.read_csv(accfile)
#     df2 = pd.read_csv(gyrofile)
df1 = pd.read_csv("E:/games/IISc-May-2019/HAPT Data Set/MobileTest/Test1.csv")
standard_scaler = preprocessing.StandardScaler()
scaled_df = standard_scaler.fit_transform(df1)
df1 = pd.DataFrame(scaled_df, columns=[ 'ax', 'ay', 'az', 'wx', 'wy', 'wz' ])

ax = df1['ax']
ay = df1['ay']
az = df1['az']
wx = df1['wx']
wy = df1['wy']
wz = df1['wz']
fs = 50
#------------------------------------------------------------------------------------------------------------------- 
#Time domain
timeAcc = np.empty([0,15])
timeGyro = np.empty([0,15])

size = 25
overlap = 20


for k in range(2):
    slider1 = Slider(size, overlap)
    slider2 = Slider(size, overlap)
    slider3 = Slider(size, overlap)
    if(k == 0):
        slider1.fit(ax)
        slider2.fit(ay)
        slider3.fit(az)
    elif(k == 1):
        slider1.fit(wx)
        slider2.fit(wy)
        slider3.fit(wz)        
    while True:
        window_data1 = slider1.slide()
        window_data2 = slider2.slide()
        window_data3 = slider3.slide()

        # do your stuff
        mean1 = np.mean(window_data1)
        variance1 = np.var(window_data1)
        median1 = np.median(window_data1)
        rms1 = np.sqrt(np.mean(window_data1**2))
#             skewdness1 = skew(window_data1)
#             kurtos1 = kurtosis(window_data1)
        ptp1 = np.ptp(window_data1)
#         rang1 = np.max(window_data1) - np.min(window_data1)
#             interq_range1 = iqr(window_data1)
#             crest_factor1 = np.max(window_data1)/rms1

        mean2 = np.mean(window_data2)
        variance2 = np.var(window_data2)
        median2 = np.median(window_data2)
        rms2 = np.sqrt(np.mean(window_data2**2))
#             skewdness2 = skew(window_data2)
#             kurtos2 = kurtosis(window_data2)
        ptp2 = np.ptp(window_data2)
#         rang2 = np.max(window_data2) - np.min(window_data2)
#             interq_range2 = iqr(window_data2)
#             crest_factor2 = np.max(window_data2)/rms2

        mean3 = np.mean(window_data3)
        variance3 = np.var(window_data3)
        median3 = np.median(window_data3)
        rms3 = np.sqrt(np.mean(window_data3**2))
#             skewdness3 = skew(window_data3)
#             kurtos3 = kurtosis(window_data3)
        ptp3 = np.ptp(window_data3)
#         rang3 = np.max(window_data3) - np.min(window_data3)
#             interq_range3 = iqr(window_data3)
#             crest_factor3 = np.max(window_data3)/rms3

#             time_dom = np.array([mean1,mean2,mean3,variance1,variance2,variance3,median1,median2,median3,
#                                  rms1,rms2,rms3,skewdness1,skewdness2,skewdness3,kurtos1,kurtos2,kurtos3,
#                                  ptp1,ptp2,ptp3,rang1,rang2,rang3,interq_range1,interq_range2,interq_range3, 
#                                  crest_factor1,crest_factor2,crest_factor3])
        time_dom = np.array([mean1,mean2,mean3,variance1,variance2,variance3,median1,median2,median3,
                             rms1,rms2,rms3,ptp1,ptp2,ptp3])
        if( k == 0 ):
            timeAcc = np.append(timeAcc, [time_dom], axis=0)
        elif ( k == 1):
            timeGyro = np.append(timeGyro, [time_dom], axis=0)

        if slider1.reached_end_of_list(): break

print(timeAcc.shape)
print(timeGyro.shape)




#Frequency Domain
Afx, Atx, Ax = signal.spectrogram(ax, fs=fs,window=signal.get_window('hann',25),noverlap=20,nperseg=25)
Afy, Aty, Ay = signal.spectrogram(ay, fs=fs,window=signal.get_window('hann',25),noverlap=20,nperseg=25)
Afz, Atz, Az = signal.spectrogram(az, fs=fs,window=signal.get_window('hann',25),noverlap=20,nperseg=25)

Wfx, Wtx, Wx = signal.spectrogram(wx, fs=fs,window=signal.get_window('hann',25),noverlap=20,nperseg=25)
Wfy, Wty, Wy = signal.spectrogram(wy, fs=fs,window=signal.get_window('hann',25),noverlap=20,nperseg=25)
Wfz, Wtz, Wz = signal.spectrogram(wz, fs=fs,window=signal.get_window('hann',25),noverlap=20,nperseg=25)

Ax = Ax.T
Ay = Ay.T
Az = Az.T
Wx = Wx.T
Wy = Wy.T
Wz = Wz.T
resA = np.concatenate((Ax, Ay, Az), axis = 1)
resW = np.concatenate((Wx, Wy, Wz), axis = 1)



for j in range(resA.shape[0]):
    sA = sorted(resA[j])
    sW = sorted(resW[j])
#     featureAcc = sA[0:15] + sA[resA.shape[1]-15:resA.shape[1]]    #For 100 features set 50 to 25
#         featureAcc.extend( timeAcc[j] )
#     featureGyr = sW[0:15] + sW[resA.shape[1]-15:resA.shape[1]]    #For 100 features set 50 to 25
#         featureGyr.extend( timeGyro[j] )
#     final = np.concatenate((featureAcc,featureGyr))

    final = np.concatenate((timeAcc[j],timeGyro[j],sA,sW))
#     print((final))

#   final = np.append( final, i )
    final = final.reshape(1,-1)
#     print((final))
    print(svm_model_linear.predict(final))


C:\Users\HP\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:2389: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)


(1116, 15)
(1116, 15)
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[3]
[2]
[2]
[2]
[2]
[3]
[3]
[3]
[3]
[2]
[2]
[3]
[3]
[3]
[3]
[3]
[3]
[3]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[3]
[3]
[3]
[3]
[3]
[3]
[3]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[2]
[3]
[3]
[3]
[3]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1